import { scrollConfig, ScrollConfig } from "./utils";
declare class Scroll {
    static config: ScrollConfig;
    static setDefaultConfig(config: scrollConfig): void;
    private element;
    private scrollWrapper;
    private scrollContent;
    private scrollContentInner;
    private scrollBarX;
    private scrollBarY;
    private width;
    private height;
    private scrollX;
    private scrollY;
    private config;
    private barHeight;
    private hasScrollX;
    private hasScrollY;
    private scrollTop;
    private scrollLeft;
    private barWidth;
    private scrollBottomCallback;
    private scrollTopCallback;
    private timeOutY;
    private timeOutX;
    constructor(el: HTMLElement, options?: scrollConfig);
    initStyle(): void;
    setBarStyle(el: HTMLDivElement, type: 'X' | 'Y'): void;
    init(): void;
    private setScrollSize;
    private setScrollY;
    private setScrollX;
    private setHasScroll;
    private setBarHeight;
    private setBarWidth;
    private setBarYMonseEvent;
    private setBarXMouseEvent;
    onScrollTop(scrollTopCallback: () => void): void;
    onScrollBottom(scrollBottomCallback: () => void): void;
    appendChild(el: Node): void;
}
export default Scroll;
